"""Adapter contract: discovery, diagnostics, snapshot, extract, validate keys, fingerprint, coverage.

All adapters open sources read-only and emit versioned canonical records.
"""

from typing import Protocol


class SourceAdapter(Protocol):
    source: str

    def discover(self): ...
    def diagnose(self): ...
    def snapshot(self, staging_dir): ...
    def extract(self, snapshot): ...
    def validate_native_keys(self, records): ...
    def fingerprint(self, snapshot): ...
    def coverage(self, snapshot): ...
